/** Aplikuje zmienne CSS motywu na :root — synchronicznie, bez FOUC */
export function applyThemeVars(t) {
  const r = document.documentElement;
  const set = (k, v) => r.style.setProperty(k, v);
  set('--hj-bg',               t.bg);
  set('--hj-bg-card',          t.bgCard);
  set('--hj-bg-input',         t.bgInput);
  set('--hj-bg-nav',           t.navBg ?? t.bgNav ?? t.bg);
  set('--hj-border',           t.border);
  set('--hj-border-sub',       t.borderSub);
  set('--hj-border-input',     t.borderInput);
  set('--hj-text',             t.text);
  set('--hj-text-muted',       t.textMuted);
  set('--hj-text-dim',         t.textDim);
  set('--hj-text-label',       t.textLabel);
  set('--hj-accent',           t.accent);
  set('--hj-accent-border',    t.accentBorder);
  set('--hj-header-bg',        t.headerBg);
  set('--hj-nav-bg',           t.navBg);
  set('--hj-scroll-track',     t.scrollTrack);
  set('--hj-scroll-thumb',     t.scrollThumb);
  set('--hj-noise',            t.noise);
  set('--hj-shadow-bot',       t.shadowBot);
  set('--hj-shadow-card',      t.shadowCard);
  if (t.shadowSoft) set('--hj-shadow-soft', t.shadowSoft);
  set('--hj-inner-div-bg',     t.innerDivBg);
  set('--hj-hp-bg',            t.hpBg);
  set('--hj-add-form',         t.addForm);
  set('--hj-modal-bg',         t.modalBg);
  set('--hj-empty-color',      t.emptyColor);
  set('--hj-sess-entry',       t.sessEntry);
  set('--hj-combat-box',       t.combatBox);
  set('--hj-spell-slot-box',   t.spellSlotBox);
  set('--hj-spell-slot-border',t.spellSlotBorder);
  set('--hj-pack-item',        t.packItem);
  set('--hj-pack-item-border', t.packItemBorder);
  set('--hj-pack-field-input', t.packFieldInput);
  set('--spell-accent',        t.spellAccent);
  set('--spell-border',        t.spellBorder);
  set('--spell-muted',         t.spellMuted);
  set('--spell-dim',           t.spellDim);
  set('--spell-text',          t.spellText);
  set('--spell-bg',            t.spellBg);
  set('--quest-reward',        t.questReward);
  set('--hj-selected-bg',      t.selectedBg);
  /* pip/text aliases — prefixed versions for new code, non-prefixed kept for global.css */
  set('--pip-prof',            t.accent);
  set('--pip-exp',             t.spellAccent);
  set('--pip-empty',           t.borderInput);
  set('--hj-pip-prof',         t.accent);
  set('--hj-pip-exp',          t.spellAccent);
  set('--hj-pip-empty',        t.borderInput);
  set('--text-label',          t.textLabel);
  set('--text-muted',          t.textMuted);
  set('--text-dim',            t.textDim);
  /* spell aliases with --hj- prefix for new code */
  set('--hj-spell-accent',     t.spellAccent);
  set('--hj-spell-border',     t.spellBorder);
  set('--hj-spell-muted',      t.spellMuted);
  set('--hj-spell-dim',        t.spellDim);
  set('--hj-spell-text',       t.spellText);
  set('--hj-spell-bg',         t.spellBg);
  set('--hj-quest-reward',     t.questReward);
}
